// AUTO-GENERATED by scripts/sync-from-lark.mjs
// Do not edit manually. Edit in Lark Base and run `npm run sync`.

export interface SectionContent {
  id: string;
  headline: string;
  subheadline?: string;
  body?: string;
  ctaText?: string;
  ctaLink?: string;
  enabled: boolean;
}

export interface TestimonialContent {
  name: string;
  industry: string;
  before: string;
  after: string;
  quote: string;
}

export interface StatContent {
  value: string;
  label: string;
}

export interface ProcessPhaseContent {
  num: string;
  title: string;
  detail: string;
  icon: string;
}

export interface SolutionContent {
  icon: string;
  title: string;
  description: string;
}

export interface MarqueeItemContent {
  text: string;
  isSeparator: boolean;
}

export interface NavLinkContent {
  label: string;
  href: string;
}

export interface ContactInfoContent {
  email: string;
  location: string;
}

export const siteContent = {
  sections: {
    hero: {
      id: "hero",
      headline: "Your campaign. One dashboard.",
      body: "We build the operating layer for influencer programs, dealer campaigns, and live commerce — without the spreadsheet chaos.",
      ctaText: "See how it works",
      ctaLink: "#solutions",
      enabled: true,
    },
    problem: {
      id: "problem",
      headline: "When was the last time you...",
      enabled: true,
    },
    solutions: {
      id: "solutions",
      headline: "You are too busy doing things a machine should do.",
      subheadline: "You did not start this to become your own assistant.",
      enabled: true,
    },
    process: {
      id: "process",
      headline: "How it works.",
      subheadline: "You tell us what drains you. We make it disappear. Two weeks from 'ugh' to 'already done'.",
      enabled: true,
    },
    proof: {
      id: "proof",
      headline: "Built for how you work.",
      subheadline: "Nothing added that you don't need.",
      enabled: true,
    },
    contact: {
      id: "contact",
      headline: "Start building.",
      subheadline: "Tell us what's broken. We'll map the fix.",
      ctaText: "Book a scoping call",
      ctaLink: "#contact",
      enabled: true,
    },
    footer: {
      id: "footer",
      headline: "adamant",
      enabled: true,
    },
  } as Record<string, SectionContent>,

  solutions: [
    {
      icon: "Network",
      title: "Workflow Systems",
      description: "One place where nothing gets forgotten. Follow-ups happen without you remembering.",
    },
    {
      icon: "LayoutDashboard",
      title: "Live Dashboards",
      description: "No more spreadsheets no one reads. Your team sees what matters, in real time.",
    },
    {
      icon: "Zap",
      title: "Automations",
      description: "Answer once. The system repeats it. Emails send themselves. Status updates flow automatically.",
    },
    {
      icon: "Wrench",
      title: "Bespoke Tools",
      description: "Get signatures tracked. Approvals routed. No more chasing people down for a yes.",
    },
  ] satisfies SolutionContent[],

  testimonials: [
    {
      name: "Thida",
      industry: "Manufacturing",
      before: "20 questions a day",
      after: "Team self-serves",
      quote: "I stopped answering questions and started building again.",
    },
    {
      name: "Min",
      industry: "Retail",
      before: "3 months, no system",
      after: "Dashboard in 3 days",
      quote: "We had a working prototype in three days. Not three months.",
    },
    {
      name: "Sarin",
      industry: "Education",
      before: "$15K quote, unused",
      after: "Fixed in one week",
      quote: "They fixed what was actually broken. Nothing more.",
    },
    {
      name: "Ploy",
      industry: "F&B",
      before: "Orders in 3 notebooks",
      after: "Auto workflow",
      quote: "No more lost orders.",
    },
  ] satisfies TestimonialContent[],

  stats: [
    { value: "47", label: "teams running" },
    { value: "2 weeks", label: "to first system" },
    { value: "30 days", label: "support included" },
    { value: "0", label: "spreadsheets needed" },
  ] satisfies StatContent[],

  processPhases: [
    {
      num: "01",
      title: "Scope",
      detail: "Map your biggest workflow bottlenecks.",
      icon: "Map",
    },
    {
      num: "02",
      title: "Build",
      detail: "Prototype in your existing tools. No migration.",
      icon: "PenTool",
    },
    {
      num: "03",
      title: "Deploy",
      detail: "Your team tests. We tune until it feels invisible.",
      icon: "Hammer",
    },
    {
      num: "04",
      title: "Run",
      detail: "Handover + support. You own the system.",
      icon: "Rocket",
    },
  ] satisfies ProcessPhaseContent[],

  marqueeItems: [
    { text: "Build once. Run forever.", isSeparator: false },
    { text: "•", isSeparator: true },
    { text: "Systems, not slogans.", isSeparator: false },
    { text: "•", isSeparator: true },
    { text: "Your team should not need you for everything.", isSeparator: false },
    { text: "•", isSeparator: true },
    { text: "Fix the workflow. Free the founder.", isSeparator: false },
    { text: "•", isSeparator: true },
  ] satisfies MarqueeItemContent[],

  navLinks: [
    { label: "Home", href: "/" },
    { label: "Problem", href: "#problem" },
    { label: "Solutions", href: "#solutions" },
    { label: "Process", href: "#process" },
    { label: "Contact", href: "#contact" },
  ] satisfies NavLinkContent[],

  contactInfo: {
    email: "hello@adamant.asia",
    location: "Remote-first",
  } satisfies ContactInfoContent,

  footerNavLinks: [
    { label: "Home", href: "/" },
    { label: "Problem", href: "#problem" },
    { label: "Solutions", href: "#solutions" },
    { label: "Process", href: "#process" },
    { label: "Contact", href: "#contact" },
  ] satisfies NavLinkContent[],

  pipelineNodes: [
    { id: "scope", label: "Scope" },
    { id: "build", label: "Build" },
    { id: "deploy", label: "Deploy" },
    { id: "run", label: "Run" },
  ] satisfies { id: string; label: string }[],
};
